services:
  rappeek-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rappeek
    restart: always
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    env_file:
      - .env
