services:
  rappeek-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rappeek
    restart: always
    ports:
      - "3000:3000"
      - "80:3000"
      - "443:3000"
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
