services:
  dozzle:
    image: ghcr.io/amir20/dozzle:latest
    container_name: dozzle
    restart: always
    ports:
      - "8080:8080"
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rappi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rappi
    restart: always
    ports:
      - "3000:3000"
      - "80:3000"
      - "443:3000"
    env_file:
      - .env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
